! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F95_LA_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LAPMR
  SUBROUTINE SLAPMR_F95(X, K, FORWRD)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(INOUT) :: K(:)
    REAL(WP), INTENT(INOUT) :: X(:, :)
    LOGICAL, OPTIONAL, INTENT(IN) :: FORWRD
  END SUBROUTINE SLAPMR_F95

  SUBROUTINE DLAPMR_F95(X, K, FORWRD)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(INOUT) :: K(:)
    REAL(WP), INTENT(INOUT) :: X(:, :)
    LOGICAL, OPTIONAL, INTENT(IN) :: FORWRD
  END SUBROUTINE DLAPMR_F95

  SUBROUTINE CLAPMR_F95(X, K, FORWRD)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(INOUT) :: K(:)
    COMPLEX(WP), INTENT(INOUT) :: X(:, :)
    LOGICAL, OPTIONAL, INTENT(IN) :: FORWRD
  END SUBROUTINE CLAPMR_F95

  SUBROUTINE ZLAPMR_F95(X, K, FORWRD)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(INOUT) :: K(:)
    COMPLEX(WP), INTENT(INOUT) :: X(:, :)
    LOGICAL, OPTIONAL, INTENT(IN) :: FORWRD
  END SUBROUTINE ZLAPMR_F95
END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LACPY

  SUBROUTINE SLACPY_F95(A, B, UPLO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: B(:, :)
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE SLACPY_F95

  SUBROUTINE DLACPY_F95(A, B, UPLO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: B(:, :)
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE DLACPY_F95

  SUBROUTINE CLACPY_F95(A, B, UPLO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(IN) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: B(:, :)
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE CLACPY_F95

  SUBROUTINE ZLACPY_F95(A, B, UPLO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(IN) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: B(:, :)
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE ZLACPY_F95
END INTERFACE LACPY

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LAMCH
  FUNCTION SLAMCH_F95(PRECISION, CMACH, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: CMACH
    REAL(WP), INTENT(IN) :: PRECISION
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP) :: SLAMCH_F95
  END FUNCTION SLAMCH_F95

  FUNCTION DLAMCH_F95(PRECISION, CMACH, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: CMACH
    REAL(WP), INTENT(IN) :: PRECISION
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP) :: DLAMCH_F95
  END FUNCTION DLAMCH_F95
END INTERFACE

INTERFACE LANGE

  FUNCTION SLANGE_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP) :: SLANGE_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN) :: A(:, :)
  END FUNCTION SLANGE_F95

  FUNCTION SLANGE1_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP) :: SLANGE1_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN) :: A(:)
  END FUNCTION SLANGE1_F95

  FUNCTION DLANGE_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP) :: DLANGE_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN) :: A(:, :)
  END FUNCTION DLANGE_F95

  FUNCTION DLANGE1_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP) :: DLANGE1_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN) :: A(:)
  END FUNCTION DLANGE1_F95

  FUNCTION CLANGE_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP) :: CLANGE_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(IN) :: A(:, :)
  END FUNCTION CLANGE_F95

  FUNCTION CLANGE1_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP) :: CLANGE1_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(IN) :: A(:)
  END FUNCTION CLANGE1_F95

  FUNCTION ZLANGE_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP) :: ZLANGE_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(IN) :: A(:, :)
  END FUNCTION ZLANGE_F95

  FUNCTION ZLANGE1_F95(A, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP) :: ZLANGE1_F95
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(IN) :: A(:)
  END FUNCTION ZLANGE1_F95
END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

#ifdef NO_LAGGE_BUG

INTERFACE LAGGE

  SUBROUTINE SLAGGE_F95(A, KL, KU, D, ISEED, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN), OPTIONAL :: KL, KU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: ISEED(4)
    REAL(WP), INTENT(IN), OPTIONAL, TARGET :: D(:)
    REAL(WP), INTENT(OUT) :: A(:, :)
  END SUBROUTINE SLAGGE_F95

  SUBROUTINE DLAGGE_F95(A, KL, KU, D, ISEED, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN), OPTIONAL :: KL, KU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: ISEED(4)
    REAL(WP), INTENT(IN), OPTIONAL, TARGET :: D(:)
    REAL(WP), INTENT(OUT) :: A(:, :)
  END SUBROUTINE DLAGGE_F95

  SUBROUTINE CLAGGE_F95(A, KL, KU, D, ISEED, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN), OPTIONAL :: KL, KU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: ISEED(4)
    REAL(WP), INTENT(IN), OPTIONAL, TARGET :: D(:)
    COMPLEX(WP), INTENT(OUT) :: A(:, :)
  END SUBROUTINE CLAGGE_F95

  SUBROUTINE ZLAGGE_F95(A, KL, KU, D, ISEED, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN), OPTIONAL :: KL, KU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: ISEED(4)
    REAL(WP), INTENT(IN), OPTIONAL, TARGET :: D(:)
    COMPLEX(WP), INTENT(OUT) :: A(:, :)
  END SUBROUTINE ZLAGGE_F95

END INTERFACE

#endif

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

END MODULE F95_LA_LAPACK
