! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F95_GE_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEEV

  SUBROUTINE SGEEV_F95(A, WR, WI, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE SGEEV_F95

  SUBROUTINE DGEEV_F95(A, WR, WI, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE DGEEV_F95

  SUBROUTINE CGEEV_F95(A, W, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE CGEEV_F95

  SUBROUTINE ZGEEV_F95(A, W, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE ZGEEV_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEESX

  SUBROUTINE SGEESX_F95(A, WR, WI, VS, SELECT, SDIM, RCONDE,      &
    &                        RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    !         USE LA_EXTERNAL
    INTERFACE
      LOGICAL FUNCTION SELECT(WR, WI)
        USE LA_PRECISION, ONLY: WP => SP
        REAL(WP), INTENT(IN) :: WR, WI
      END FUNCTION SELECT
    END INTERFACE
    !
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE, RCONDV
    REAL(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE SGEESX_F95

  SUBROUTINE DGEESX_F95(A, WR, WI, VS, SELECT, SDIM, RCONDE,      &
    &                        RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    !         USE LA_EXTERNAL
    INTERFACE
      LOGICAL FUNCTION SELECT(WR, WI)
        USE LA_PRECISION, ONLY: WP => DP
        REAL(WP), INTENT(IN) :: WR, WI
      END FUNCTION SELECT
    END INTERFACE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE, RCONDV
    REAL(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE DGEESX_F95

  SUBROUTINE CGEESX_F95(A, W, VS, SELECT, SDIM, RCONDE, RCONDV,   &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTERFACE
      LOGICAL FUNCTION SELECT(W)
        USE LA_PRECISION, ONLY: WP => SP
        COMPLEX(WP), INTENT(IN) :: W
      END FUNCTION SELECT
    END INTERFACE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE, RCONDV
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE CGEESX_F95

  SUBROUTINE ZGEESX_F95(A, W, VS, SELECT, SDIM, RCONDE, RCONDV,   &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTERFACE
      LOGICAL FUNCTION SELECT(W)
        USE LA_PRECISION, ONLY: WP => DP
        COMPLEX(WP), INTENT(IN) :: W
      END FUNCTION SELECT
    END INTERFACE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE, RCONDV
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE ZGEESX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GGESX

  SUBROUTINE SGGESX_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,     &
    &                        SELECT, SDIM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHAR, ALPHAI, BETA)
        USE LA_PRECISION, ONLY: WP => SP
        REAL(WP), INTENT(IN) :: ALPHAR, ALPHAI, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE(2), RCONDV(2)
  END SUBROUTINE SGGESX_F95

  SUBROUTINE DGGESX_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,     &
    &                        SELECT, SDIM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHAR, ALPHAI, BETA)
        USE LA_PRECISION, ONLY: WP => DP
        REAL(WP), INTENT(IN) :: ALPHAR, ALPHAI, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE(2), RCONDV(2)
  END SUBROUTINE DGGESX_F95

  SUBROUTINE CGGESX_F95(A, B, ALPHA, BETA, VSL, VSR, SELECT, SDIM,&
    &                        RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHA, BETA)
        USE LA_PRECISION, ONLY: WP => SP
        COMPLEX(WP), INTENT(IN) :: ALPHA, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE(2), RCONDV(2)
  END SUBROUTINE CGGESX_F95

  SUBROUTINE ZGGESX_F95(A, B, ALPHA, BETA, VSL, VSR, SELECT, SDIM,&
    &                        RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHA, BETA)
        USE LA_PRECISION, ONLY: WP => DP
        COMPLEX(WP), INTENT(IN) :: ALPHA, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
    REAL(WP), INTENT(OUT), OPTIONAL :: RCONDE(2), RCONDV(2)
  END SUBROUTINE ZGGESX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GGES

  SUBROUTINE SGGES_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,      &
    &                       SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHAR, ALPHAI, BETA)
        USE LA_PRECISION, ONLY: WP => SP
        REAL(WP), INTENT(IN) :: ALPHAR, ALPHAI, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
  END SUBROUTINE SGGES_F95

  SUBROUTINE DGGES_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,      &
    &                       SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHAR, ALPHAI, BETA)
        USE LA_PRECISION, ONLY: WP => DP
        REAL(WP), INTENT(IN) :: ALPHAR, ALPHAI, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
  END SUBROUTINE DGGES_F95

  SUBROUTINE CGGES_F95(A, B, ALPHA, BETA, VSL, VSR, SELECT, SDIM, &
    &                       INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHA, BETA)
        USE LA_PRECISION, ONLY: WP => SP
        COMPLEX(WP), INTENT(IN) :: ALPHA, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
  END SUBROUTINE CGGES_F95

  SUBROUTINE ZGGES_F95(A, B, ALPHA, BETA, VSL, VSR, SELECT, SDIM, &
    &                       INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: SDIM
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VSL(:, :), VSR(:, :)
    INTERFACE
      LOGICAL FUNCTION SELECT(ALPHA, BETA)
        USE LA_PRECISION, ONLY: WP => DP
        COMPLEX(WP), INTENT(IN) :: ALPHA, BETA
      END FUNCTION SELECT
    END INTERFACE
    OPTIONAL :: SELECT
  END SUBROUTINE ZGGES_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEES

  SUBROUTINE SGEES_F95(A, WR, WI, VS, SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    !         USE LA_EXTERNAL, ONLY: SELECT
    INTERFACE
      LOGICAL FUNCTION SELECT(WR, WI)
        USE LA_PRECISION, ONLY: WP => SP
        REAL(WP), INTENT(IN) :: WR, WI
      END FUNCTION SELECT
    END INTERFACE

    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE SGEES_F95

  SUBROUTINE DGEES_F95(A, WR, WI, VS, SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    !         USE LA_EXTERNAL, ONLY: SELECT
    INTERFACE
      LOGICAL FUNCTION SELECT(WR, WI)
        USE LA_PRECISION, ONLY: WP => DP
        REAL(WP), INTENT(IN) :: WR, WI
      END FUNCTION SELECT
    END INTERFACE

    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE DGEES_F95

  SUBROUTINE CGEES_F95(A, W, VS, SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTERFACE
      LOGICAL FUNCTION SELECT(W)
        USE LA_PRECISION, ONLY: WP => SP
        COMPLEX(WP), INTENT(IN) :: W
      END FUNCTION SELECT
    END INTERFACE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE CGEES_F95

  SUBROUTINE ZGEES_F95(A, W, VS, SELECT, SDIM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTERFACE
      LOGICAL FUNCTION SELECT(W)
        USE LA_PRECISION, ONLY: WP => DP
        COMPLEX(WP), INTENT(IN) :: W
      END FUNCTION SELECT
    END INTERFACE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, SDIM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VS(:, :)
    OPTIONAL :: SELECT
  END SUBROUTINE ZGEES_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GELS

  SUBROUTINE SGELS_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE SGELS_F95

  SUBROUTINE SGELS1_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE SGELS1_F95

  SUBROUTINE DGELS_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE DGELS_F95

  SUBROUTINE DGELS1_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE DGELS1_F95

  SUBROUTINE CGELS_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE CGELS_F95

  SUBROUTINE CGELS1_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE CGELS1_F95

  SUBROUTINE ZGELS_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE ZGELS_F95

  SUBROUTINE ZGELS1_F95(A, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE ZGELS1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEGV

  SUBROUTINE SGEGV_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ALPHAR(:), ALPHAI(:),      &
    &                                       BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE SGEGV_F95

  SUBROUTINE DGEGV_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ALPHAR(:), ALPHAI(:),      &
    &                                       BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE DGEGV_F95

  SUBROUTINE CGEGV_F95(A, B, ALPHA, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE CGEGV_F95

  SUBROUTINE ZGEGV_F95(A, B, ALPHA, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE ZGEGV_F95
END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEGS

  SUBROUTINE SGEGS_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,      &
    &                       INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ALPHAR(:), ALPHAI(:),      &
    &                                       BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VSL(:, :), VSR(:, :)
  END SUBROUTINE SGEGS_F95

  SUBROUTINE DGEGS_F95(A, B, ALPHAR, ALPHAI, BETA, VSL, VSR,      &
    &                       INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ALPHAR(:), ALPHAI(:),      &
    &                                       BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VSL(:, :), VSR(:, :)
  END SUBROUTINE DGEGS_F95

  SUBROUTINE CGEGS_F95(A, B, ALPHA, BETA, VSL, VSR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VSL(:, :),       &
    &                                                  VSR(:, :)
  END SUBROUTINE CGEGS_F95

  SUBROUTINE ZGEGS_F95(A, B, ALPHA, BETA, VSL, VSR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VSL(:, :),       &
    &                                                  VSR(:, :)
  END SUBROUTINE ZGEGS_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GESV

  SUBROUTINE SGESV_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE SGESV_F95

  SUBROUTINE SGESV1_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE SGESV1_F95

  SUBROUTINE DGESV_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE DGESV_F95

  SUBROUTINE DGESV1_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE DGESV1_F95

  SUBROUTINE CGESV_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE CGESV_F95

  SUBROUTINE CGESV1_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE CGESV1_F95

  SUBROUTINE ZGESV_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE ZGESV_F95

  SUBROUTINE ZGESV1_F95(A, B, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE ZGESV1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GESVX

  SUBROUTINE SGESVX_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R, &
    &                        C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE SGESVX_F95

  SUBROUTINE SGESVX1_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R,&
    &                         C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE SGESVX1_F95

  SUBROUTINE DGESVX_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R, &
    &                        C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE DGESVX_F95

  SUBROUTINE DGESVX1_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R,&
    &                         C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE DGESVX1_F95

  SUBROUTINE CGESVX_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R, &
    &                        C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE CGESVX_F95

  SUBROUTINE CGESVX1_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R,&
    &                         C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE CGESVX1_F95

  SUBROUTINE ZGESVX_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R, &
    &                        C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE ZGESVX_F95

  SUBROUTINE ZGESVX1_F95(A, B, X, AF, IPIV, FACT, TRANS, EQUED, R,&
    &                         C, FERR, BERR, RCOND, RPVGRW, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS, FACT
    CHARACTER(LEN=1), INTENT(INOUT), OPTIONAL :: EQUED
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, RPVGRW
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(INOUT), OPTIONAL :: C(:), R(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE ZGESVX1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GETRF

  SUBROUTINE SGETRF_F95(A, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE SGETRF_F95

  SUBROUTINE DGETRF_F95(A, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE DGETRF_F95

  SUBROUTINE CGETRF_F95(A, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE CGETRF_F95

  SUBROUTINE ZGETRF_F95(A, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE ZGETRF_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GETRS

  SUBROUTINE SGETRS_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE SGETRS_F95

  SUBROUTINE SGETRS1_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE SGETRS1_F95

  SUBROUTINE DGETRS_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE DGETRS_F95

  SUBROUTINE DGETRS1_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE DGETRS1_F95

  SUBROUTINE CGETRS_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE CGETRS_F95

  SUBROUTINE CGETRS1_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE CGETRS1_F95

  SUBROUTINE ZGETRS_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE ZGETRS_F95

  SUBROUTINE ZGETRS1_F95(A, IPIV, B, TRANS, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE ZGETRS1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GETRI

  SUBROUTINE SGETRI_F95(A, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE SGETRI_F95

  SUBROUTINE DGETRI_F95(A, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE DGETRI_F95

  SUBROUTINE CGETRI_F95(A, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE CGETRI_F95

  SUBROUTINE ZGETRI_F95(A, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE ZGETRI_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GERFS

  SUBROUTINE SGERFS_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,     &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(IN) :: A(:, :), AF(:, :), B(:, :)
    REAL(WP), INTENT(INOUT) :: X(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE SGERFS_F95

  SUBROUTINE SGERFS1_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,    &
    &                         INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(IN) :: A(:, :), AF(:, :)
    REAL(WP), INTENT(IN) :: B(:)
    REAL(WP), INTENT(INOUT) :: X(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE SGERFS1_F95

  SUBROUTINE DGERFS_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,     &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(IN) :: A(:, :), AF(:, :), B(:, :)
    REAL(WP), INTENT(INOUT) :: X(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE DGERFS_F95

  SUBROUTINE DGERFS1_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,    &
    &                         INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    REAL(WP), INTENT(IN) :: A(:, :), AF(:, :)
    REAL(WP), INTENT(IN) :: B(:)
    REAL(WP), INTENT(INOUT) :: X(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE DGERFS1_F95

  SUBROUTINE CGERFS_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,     &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(IN) :: A(:, :), AF(:, :), B(:, :)
    COMPLEX(WP), INTENT(INOUT) :: X(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE CGERFS_F95

  SUBROUTINE CGERFS1_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,    &
    &                         INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(IN) :: A(:, :), AF(:, :)
    COMPLEX(WP), INTENT(IN) :: B(:)
    COMPLEX(WP), INTENT(INOUT) :: X(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE CGERFS1_F95

  SUBROUTINE ZGERFS_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,     &
    &                        INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(IN) :: A(:, :), AF(:, :), B(:, :)
    COMPLEX(WP), INTENT(INOUT) :: X(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE ZGERFS_F95

  SUBROUTINE ZGERFS1_F95(A, AF, IPIV, B, X, TRANS, FERR, BERR,    &
    &                         INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: TRANS
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(IN) :: IPIV(:)
    COMPLEX(WP), INTENT(IN) :: A(:, :), AF(:, :)
    COMPLEX(WP), INTENT(IN) :: B(:)
    COMPLEX(WP), INTENT(INOUT) :: X(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR, BERR
  END SUBROUTINE ZGERFS1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEEQU

  SUBROUTINE SGEEQU_F95(A, R, C, ROWCND, COLCND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: AMAX, COLCND, ROWCND
    REAL(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: C(:), R(:)
  END SUBROUTINE SGEEQU_F95

  SUBROUTINE DGEEQU_F95(A, R, C, ROWCND, COLCND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: AMAX, COLCND, ROWCND
    REAL(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: C(:), R(:)
  END SUBROUTINE DGEEQU_F95

  SUBROUTINE CGEEQU_F95(A, R, C, ROWCND, COLCND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: AMAX, COLCND, ROWCND
    COMPLEX(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: C(:), R(:)
  END SUBROUTINE CGEEQU_F95

  SUBROUTINE ZGEEQU_F95(A, R, C, ROWCND, COLCND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: AMAX, COLCND, ROWCND
    COMPLEX(WP), INTENT(IN) :: A(:, :)
    REAL(WP), INTENT(OUT) :: C(:), R(:)
  END SUBROUTINE ZGEEQU_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GELSX

  SUBROUTINE SGELSX_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSX_F95

  SUBROUTINE SGELSX1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSX1_F95

  SUBROUTINE DGELSX_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSX_F95

  SUBROUTINE DGELSX1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSX1_F95

  SUBROUTINE CGELSX_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSX_F95

  SUBROUTINE CGELSX1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSX1_F95

  SUBROUTINE ZGELSX_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSX_F95

  SUBROUTINE ZGELSX1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    INTEGER, INTENT(OUT), OPTIONAL :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSX1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GELSS

  SUBROUTINE SGELSS_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSS_F95

  SUBROUTINE SGELSS1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSS1_F95

  SUBROUTINE DGELSS_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSS_F95

  SUBROUTINE DGELSS1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSS1_F95

  SUBROUTINE CGELSS_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSS_F95

  SUBROUTINE CGELSS1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSS1_F95

  SUBROUTINE ZGELSS_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSS_F95

  SUBROUTINE ZGELSS1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSS1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GELSD

  SUBROUTINE SGELSD_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSD_F95

  SUBROUTINE SGELSD1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSD1_F95

  SUBROUTINE DGELSD_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSD_F95

  SUBROUTINE DGELSD1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSD1_F95

  SUBROUTINE CGELSD_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSD_F95

  SUBROUTINE CGELSD1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSD1_F95

  SUBROUTINE ZGELSD_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSD_F95

  SUBROUTINE ZGELSD1_F95(A, B, RANK, S, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(IN), OPTIONAL :: RANK
    REAL(WP), INTENT(OUT), OPTIONAL :: S(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSD1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GESDD

  SUBROUTINE SGESDD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE SGESDD_F95

  SUBROUTINE DGESDD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE DGESDD_F95

  SUBROUTINE CGESDD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE CGESDD_F95

  SUBROUTINE ZGESDD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE ZGESDD_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GELSY

  SUBROUTINE SGELSY_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSY_F95

  SUBROUTINE SGELSY1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGELSY1_F95

  SUBROUTINE DGELSY_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSY_F95

  SUBROUTINE DGELSY1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGELSY1_F95

  SUBROUTINE CGELSY_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSY_F95

  SUBROUTINE CGELSY1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGELSY1_F95

  SUBROUTINE ZGELSY_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSY_F95

  SUBROUTINE ZGELSY1_F95(A, B, RANK, JPVT, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
    INTEGER, INTENT(OUT), OPTIONAL :: RANK
    INTEGER, INTENT(INOUT), OPTIONAL, TARGET :: JPVT(:)
    REAL(WP), INTENT(IN), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGELSY1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GEEVX

  SUBROUTINE SGEEVX_F95(A, WR, WI, VL, VR, BALANC, ILO, IHI,      &
    &                        SCALE, ABNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, ILO, IHI
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM
    REAL(WP), INTENT(OUT), OPTIONAL :: SCALE(:), RCONDE(:),        &
    &                                      RCONDV(:)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE SGEEVX_F95

  SUBROUTINE DGEEVX_F95(A, WR, WI, VL, VR, BALANC, ILO, IHI,      &
    &                        SCALE, ABNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, ILO, IHI
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM
    REAL(WP), INTENT(OUT), OPTIONAL :: SCALE(:), RCONDE(:),        &
    &                                      RCONDV(:)
    REAL(WP), INTENT(OUT) :: WR(:), WI(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE DGEEVX_F95

  SUBROUTINE CGEEVX_F95(A, W, VL, VR, BALANC, ILO, IHI, SCALE,    &
    &                        ABNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, ILO, IHI
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM
    REAL(WP), INTENT(OUT), OPTIONAL :: SCALE(:), RCONDE(:),        &
    &                                      RCONDV(:)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE CGEEVX_F95

  SUBROUTINE ZGEEVX_F95(A, W, VL, VR, BALANC, ILO, IHI, SCALE,    &
    &                        ABNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, ILO, IHI
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM
    REAL(WP), INTENT(OUT), OPTIONAL :: SCALE(:), RCONDE(:),        &
    &                                      RCONDV(:)
    COMPLEX(WP), INTENT(OUT) :: W(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE ZGEEVX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GGEVX

  SUBROUTINE SGGEVX_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR,       &
    &                        BALANC, ILO, IHI, LSCALE, RSCALE, ABNRM,  &
    &                        BBNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: ILO, IHI
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM, BBNRM
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:)
    REAL(WP), INTENT(OUT) :: BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: LSCALE(:), RSCALE(:),        &
    &                                     RCONDE(:), RCONDV(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE SGGEVX_F95

  SUBROUTINE DGGEVX_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR,       &
    &                        BALANC, ILO, IHI, LSCALE, RSCALE, ABNRM,  &
    &                        BBNRM, RCONDE, RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: ILO, IHI
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM, BBNRM
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:)
    REAL(WP), INTENT(OUT) :: BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: LSCALE(:), RSCALE(:),        &
    &                                     RCONDE(:), RCONDV(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE DGGEVX_F95

  SUBROUTINE CGGEVX_F95(A, B, ALPHA, BETA, VL, VR, BALANC, ILO,   &
    &                        IHI, LSCALE, RSCALE, ABNRM, BBNRM, RCONDE,&
    &                        RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: ILO, IHI
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM, BBNRM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:)
    COMPLEX(WP), INTENT(OUT) :: BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: LSCALE(:), RSCALE(:),       &
    &                                      RCONDE(:), RCONDV(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE CGGEVX_F95

  SUBROUTINE ZGGEVX_F95(A, B, ALPHA, BETA, VL, VR, BALANC, ILO,   &
    &                        IHI, LSCALE, RSCALE, ABNRM, BBNRM, RCONDE,&
    &                        RCONDV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: BALANC
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: ILO, IHI
    REAL(WP), INTENT(OUT), OPTIONAL :: ABNRM, BBNRM
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:)
    COMPLEX(WP), INTENT(OUT) :: BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL :: LSCALE(:), RSCALE(:),       &
    &                                      RCONDE(:), RCONDV(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL :: VL(:, :), VR(:, :)
  END SUBROUTINE ZGGEVX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GGEV

  SUBROUTINE SGGEV_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE SGGEV_F95

  SUBROUTINE DGGEV_F95(A, B, ALPHAR, ALPHAI, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: ALPHAR(:), ALPHAI(:), BETA(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE DGGEV_F95

  SUBROUTINE CGGEV_F95(A, B, ALPHA, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE CGGEV_F95

  SUBROUTINE ZGGEV_F95(A, B, ALPHA, BETA, VL, VR, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: ALPHA(:), BETA(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: VL(:, :), VR(:, :)
  END SUBROUTINE ZGGEV_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GESVD

  SUBROUTINE SGESVD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE SGESVD_F95

  SUBROUTINE DGESVD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE DGESVD_F95

  SUBROUTINE CGESVD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE CGESVD_F95

  SUBROUTINE ZGESVD_F95(A, S, U, VT, WW, JOB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: JOB
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: S(:)
    REAL(WP), INTENT(OUT), OPTIONAL, TARGET :: WW(:)
    COMPLEX(WP), INTENT(OUT), OPTIONAL, TARGET :: U(:, :), VT(:, :)
  END SUBROUTINE ZGESVD_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE GGLSE

  SUBROUTINE SGGLSE_F95(A, B, C, D, X, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :), C(:), D(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SGGLSE_F95

  SUBROUTINE DGGLSE_F95(A, B, C, D, X, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :), C(:), D(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DGGLSE_F95

  SUBROUTINE CGGLSE_F95(A, B, C, D, X, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :), C(:), D(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE CGGLSE_F95

  SUBROUTINE ZGGLSE_F95(A, B, C, D, X, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :), C(:), D(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE ZGGLSE_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

END MODULE F95_GE_LAPACK
