! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F95_SY_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYSWAPR
  SUBROUTINE SSYSWAPR_F95(A, I1, I2, UPLO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :)
    INTEGER, INTENT(IN) :: I1, I2
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE SSYSWAPR_F95

  SUBROUTINE DSYSWAPR_F95(A, I1, I2, UPLO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :)
    INTEGER, INTENT(IN) :: I1, I2
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE DSYSWAPR_F95

  SUBROUTINE CSYSWAPR_F95(A, I1, I2, UPLO)
    USE LA_PRECISION, ONLY: WP => SP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    INTEGER, INTENT(IN) :: I1, I2
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE CSYSWAPR_F95

  SUBROUTINE ZSYSWAPR_F95(A, I1, I2, UPLO)
    USE LA_PRECISION, ONLY: WP => DP
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
    INTEGER, INTENT(IN) :: I1, I2
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
  END SUBROUTINE ZSYSWAPR_F95
END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYTRF

  SUBROUTINE SSYTRF_F95(A, UPLO, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE SSYTRF_F95

  SUBROUTINE DSYTRF_F95(A, UPLO, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE DSYTRF_F95

  SUBROUTINE CSYTRF_F95(A, UPLO, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE CSYTRF_F95

  SUBROUTINE ZSYTRF_F95(A, UPLO, IPIV, RCOND, NORM, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), OPTIONAL, INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: NORM
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :)
  END SUBROUTINE ZSYTRF_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYSVX

  SUBROUTINE SSYSVX_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR, BERR,&
    &                        RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    REAL(WP), INTENT(IN) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE SSYSVX_F95

  SUBROUTINE SSYSVX1_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR,     &
    &                         BERR, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, FERR, BERR
    REAL(WP), INTENT(IN) :: A(:, :), B(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
  END SUBROUTINE SSYSVX1_F95

  SUBROUTINE DSYSVX_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR, BERR,&
    &                        RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    REAL(WP), INTENT(IN) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE DSYSVX_F95

  SUBROUTINE DSYSVX1_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR,     &
    &                         BERR, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, FERR, BERR
    REAL(WP), INTENT(IN) :: A(:, :), B(:)
    REAL(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
  END SUBROUTINE DSYSVX1_F95

  SUBROUTINE CSYSVX_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR, BERR,&
    &                        RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    COMPLEX(WP), INTENT(IN) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE CSYSVX_F95

  SUBROUTINE CSYSVX1_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR,     &
    &                         BERR, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, FERR, BERR
    COMPLEX(WP), INTENT(IN) :: A(:, :), B(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
  END SUBROUTINE CSYSVX1_F95

  SUBROUTINE ZSYSVX_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR, BERR,&
    &                        RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND
    COMPLEX(WP), INTENT(IN) :: A(:, :), B(:, :)
    COMPLEX(WP), INTENT(OUT) :: X(:, :)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
    REAL(WP), INTENT(OUT), OPTIONAL :: FERR(:), BERR(:)
  END SUBROUTINE ZSYSVX_F95

  SUBROUTINE ZSYSVX1_F95(A, B, X, UPLO, AF, IPIV, FACT, FERR,     &
    &                         BERR, RCOND, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO, FACT
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(OUT), OPTIONAL :: RCOND, FERR, BERR
    COMPLEX(WP), INTENT(IN) :: A(:, :), B(:)
    COMPLEX(WP), INTENT(OUT) :: X(:)
    INTEGER, INTENT(INOUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT), OPTIONAL :: AF(:, :)
  END SUBROUTINE ZSYSVX1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYSV

  SUBROUTINE SSYSV_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE SSYSV_F95

  SUBROUTINE SSYSV1_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE SSYSV1_F95

  SUBROUTINE DSYSV_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE DSYSV_F95

  SUBROUTINE DSYSV1_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE DSYSV1_F95

  SUBROUTINE CSYSV_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE CSYSV_F95

  SUBROUTINE CSYSV1_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE CSYSV1_F95

  SUBROUTINE ZSYSV_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:, :)
  END SUBROUTINE ZSYSV_F95

  SUBROUTINE ZSYSV1_F95(A, B, UPLO, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    INTEGER, INTENT(OUT), OPTIONAL :: IPIV(:)
    COMPLEX(WP), INTENT(INOUT) :: A(:, :), B(:)
  END SUBROUTINE ZSYSV1_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYEV

  SUBROUTINE SSYEV_F95(A, W, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE SSYEV_F95

  SUBROUTINE DSYEV_F95(A, W, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE DSYEV_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYEVD

  SUBROUTINE SSYEVD_F95(A, W, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE SSYEVD_F95

  SUBROUTINE DSYEVD_F95(A, W, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE DSYEVD_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYEVR

  SUBROUTINE SSYEVR_F95(A, W, JOBZ, UPLO, VL, VU, IL, IU, M,      &
    &                        ISUPPZ, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU
    INTEGER, INTENT(OUT), OPTIONAL :: M
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: ISUPPZ(:)
  END SUBROUTINE SSYEVR_F95

  SUBROUTINE DSYEVR_F95(A, W, JOBZ, UPLO, VL, VU, IL, IU, M,      &
    &                        ISUPPZ, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU
    INTEGER, INTENT(OUT), OPTIONAL :: M
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: ISUPPZ(:)
  END SUBROUTINE DSYEVR_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYEVX

  SUBROUTINE SSYEVX_F95(A, W, JOBZ, UPLO, VL, VU, IL, IU, M,      &
    &                        IFAIL, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, M
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: IFAIL(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE SSYEVX_F95

  SUBROUTINE DSYEVX_F95(A, W, JOBZ, UPLO, VL, VU, IL, IU, M,      &
    &                        IFAIL, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU
    INTEGER, INTENT(OUT), OPTIONAL :: INFO, M
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: IFAIL(:)
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE DSYEVX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYGST

  SUBROUTINE SSYGST_F95(A, B, ITYPE, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(IN) :: B(:, :)
  END SUBROUTINE SSYGST_F95

  SUBROUTINE DSYGST_F95(A, B, ITYPE, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(IN) :: B(:, :)
  END SUBROUTINE DSYGST_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYGV

  SUBROUTINE SSYGV_F95(A, B, W, ITYPE, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE SSYGV_F95

  SUBROUTINE DSYGV_F95(A, B, W, ITYPE, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
  END SUBROUTINE DSYGV_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYGVX

  SUBROUTINE SSYGVX_F95(A, B, W, ITYPE, JOBZ, UPLO, VL, VU, IL,  &
    &                         IU, M, IFAIL, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU, ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: M
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: IFAIL(:)
  END SUBROUTINE SSYGVX_F95

  SUBROUTINE DSYGVX_F95(A, B, W, ITYPE, JOBZ, UPLO, VL, VU, IL,  &
    &                         IU, M, IFAIL, ABSTOL, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(IN), OPTIONAL :: ABSTOL, VL, VU
    INTEGER, INTENT(IN), OPTIONAL :: IL, IU, ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: M
    INTEGER, INTENT(OUT), OPTIONAL, TARGET :: IFAIL(:)
  END SUBROUTINE DSYGVX_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYGVD

  SUBROUTINE SSYGVD_F95(A, B, W, ITYPE, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE SSYGVD_F95

  SUBROUTINE DSYGVD_F95(A, B, W, ITYPE, JOBZ, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    REAL(WP), INTENT(INOUT) :: A(:, :), B(:, :)
    REAL(WP), INTENT(OUT) :: W(:)
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: JOBZ, UPLO
    INTEGER, INTENT(IN), OPTIONAL :: ITYPE
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
  END SUBROUTINE DSYGVD_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE SYTRD

  SUBROUTINE SSYTRD_F95(A, TAU, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: TAU(:)
  END SUBROUTINE SSYTRD_F95

  SUBROUTINE DSYTRD_F95(A, TAU, UPLO, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: UPLO
    INTEGER, INTENT(OUT), OPTIONAL :: INFO
    REAL(WP), INTENT(INOUT) :: A(:, :)
    REAL(WP), INTENT(OUT) :: TAU(:)
  END SUBROUTINE DSYTRD_F95

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

END MODULE F95_SY_LAPACK
