! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_TP_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TPTRI

  SUBROUTINE STPTRI(UPLO, DIAG, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE STPTRI

  SUBROUTINE DTPTRI(UPLO, DIAG, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE DTPTRI

  SUBROUTINE CTPTRI(UPLO, DIAG, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE CTPTRI

  SUBROUTINE ZTPTRI(UPLO, DIAG, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE ZTPTRI

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TPRFS

  SUBROUTINE STPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,&
 &                   FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STPRFS

  SUBROUTINE DTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,&
 &                   FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTPRFS

  SUBROUTINE CTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,&
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTPRFS

  SUBROUTINE ZTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,&
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTPRFS

  MODULE PROCEDURE STPRFS1
  MODULE PROCEDURE DTPRFS1
  MODULE PROCEDURE CTPRFS1
  MODULE PROCEDURE ZTPRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TPCON

  SUBROUTINE STPCON(NORM, UPLO, DIAG, N, AP, RCOND, WORK, IWORK,   &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STPCON

  SUBROUTINE DTPCON(NORM, UPLO, DIAG, N, AP, RCOND, WORK, IWORK,   &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTPCON

  SUBROUTINE CTPCON(NORM, UPLO, DIAG, N, AP, RCOND, WORK, RWORK,   &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTPCON

  SUBROUTINE ZTPCON(NORM, UPLO, DIAG, N, AP, RCOND, WORK, RWORK,   &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTPCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TPTRS

  SUBROUTINE STPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE STPTRS

  SUBROUTINE DTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DTPTRS

  SUBROUTINE CTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CTPTRS

  SUBROUTINE ZTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZTPTRS

  MODULE PROCEDURE STPTRS1
  MODULE PROCEDURE DTPTRS1
  MODULE PROCEDURE CTPTRS1
  MODULE PROCEDURE ZTPTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE STPRFS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X,    &
&                    LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AP(*), B(*), X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE STPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         X, LDX, FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE STPRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL STPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,   &
&                FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE STPRFS1

SUBROUTINE DTPRFS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X,    &
&                    LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AP(*), B(*), X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE DTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         X, LDX, FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE DTPRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL DTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,   &
&                FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE DTPRFS1

SUBROUTINE CTPRFS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X,    &
&                    LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AP(*), B(*), X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         X, LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CTPRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL CTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,   &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE CTPRFS1

SUBROUTINE ZTPRFS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X,    &
&                    LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AP(*), B(*), X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         X, LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AP(*), B(LDB, *), X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZTPRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL ZTPRFS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, X, LDX,   &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE ZTPRFS1

SUBROUTINE STPTRS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,       &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE STPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE STPTRS
  END INTERFACE
  CALL STPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE STPTRS1

SUBROUTINE DTPTRS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,       &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE DTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE DTPTRS
  END INTERFACE
  CALL DTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE DTPTRS1

SUBROUTINE CTPTRS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,       &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE CTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE CTPTRS
  END INTERFACE
  CALL CTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE CTPTRS1

SUBROUTINE ZTPTRS1(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,       &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE ZTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB,  &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE ZTPTRS
  END INTERFACE
  CALL ZTPTRS(UPLO, TRANS, DIAG, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE ZTPTRS1

END MODULE F77_TP_LAPACK
