! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_TB_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TBRFS

  SUBROUTINE STBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, X, LDX, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STBRFS

  SUBROUTINE DTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, X, LDX, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTBRFS

  SUBROUTINE CTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, X, LDX, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTBRFS

  SUBROUTINE ZTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, X, LDX, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTBRFS

  MODULE PROCEDURE STBRFS1
  MODULE PROCEDURE DTBRFS1
  MODULE PROCEDURE CTBRFS1
  MODULE PROCEDURE ZTBRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TBCON

  SUBROUTINE STBCON(NORM, UPLO, DIAG, N, KD, AB, LDAB, RCOND, WORK,&
 &                   IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AB(LDAB, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STBCON

  SUBROUTINE DTBCON(NORM, UPLO, DIAG, N, KD, AB, LDAB, RCOND, WORK,&
 &                   IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AB(LDAB, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTBCON

  SUBROUTINE CTBCON(NORM, UPLO, DIAG, N, KD, AB, LDAB, RCOND, WORK,&
 &                   RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTBCON

  SUBROUTINE ZTBCON(NORM, UPLO, DIAG, N, KD, AB, LDAB, RCOND, WORK,&
 &                   RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTBCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TBTRS

  SUBROUTINE STBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AB(LDAB, *)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE STBTRS

  SUBROUTINE DTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AB(LDAB, *)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DTBTRS

  SUBROUTINE CTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CTBTRS

  SUBROUTINE ZTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,   &
 &                   LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZTBTRS

  MODULE PROCEDURE STBTRS1
  MODULE PROCEDURE DTBTRS1
  MODULE PROCEDURE CTBTRS1
  MODULE PROCEDURE ZTBTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE STBRFS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, X, LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AB(LDAB, *), B(*), X(*)
  REAL(WP), INTENT(IN) :: WORK(*)
  INTERFACE
    SUBROUTINE STBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, X, LDX, FERR, BERR, WORK, IWORK, &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
      REAL(WP), INTENT(IN) :: WORK(*)
    END SUBROUTINE STBRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL STBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                X, LDX, FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE STBRFS1

SUBROUTINE DTBRFS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, X, LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AB(LDAB, *), B(*), X(*)
  REAL(WP), INTENT(IN) :: WORK(*)
  INTERFACE
    SUBROUTINE DTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, X, LDX, FERR, BERR, WORK, IWORK, &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
      REAL(WP), INTENT(IN) :: WORK(*)
    END SUBROUTINE DTBRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL DTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                X, LDX, FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE DTBRFS1

SUBROUTINE CTBRFS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, X, LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(*), X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, X, LDX, FERR, BERR, WORK, RWORK, &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CTBRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL CTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                X, LDX, FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE CTBRFS1

SUBROUTINE ZTBRFS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, X, LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(*), X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, X, LDX, FERR, BERR, WORK, RWORK, &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AB(LDAB, *), B(LDB, *), X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZTBRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL ZTBRFS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                X, LDX, FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE ZTBRFS1

SUBROUTINE STBTRS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AB(LDAB, *)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE STBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AB(LDAB, *)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE STBTRS
  END INTERFACE
  CALL STBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                INFO)
END SUBROUTINE STBTRS1

SUBROUTINE DTBTRS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AB(LDAB, *)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE DTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AB(LDAB, *)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE DTBTRS
  END INTERFACE
  CALL DTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                INFO)
END SUBROUTINE DTBTRS1

SUBROUTINE CTBTRS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE CTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE CTBTRS
  END INTERFACE
  CALL CTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                INFO)
END SUBROUTINE CTBTRS1

SUBROUTINE ZTBTRS1(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B,  &
&                    LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE ZTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB,&
&                         B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: KD, LDAB, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AB(LDAB, *)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE ZTBTRS
  END INTERFACE
  CALL ZTBTRS(UPLO, TRANS, DIAG, N, KD, NRHS, AB, LDAB, B, LDB, &
&                INFO)
END SUBROUTINE ZTBTRS1

END MODULE F77_TB_LAPACK
