! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_SP_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPGST

  SUBROUTINE SSPGST(ITYPE, UPLO, N, AP, BP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: ITYPE, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: BP(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE SSPGST

  SUBROUTINE DSPGST(ITYPE, UPLO, N, AP, BP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: ITYPE, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: BP(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE DSPGST

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPTRD

  SUBROUTINE SSPTRD(UPLO, N, AP, D, E, TAU, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: D(*), E(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: TAU(*)
  END SUBROUTINE SSPTRD

  SUBROUTINE DSPTRD(UPLO, N, AP, D, E, TAU, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: D(*), E(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: TAU(*)
  END SUBROUTINE DSPTRD

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPTRI

  SUBROUTINE SSPTRI(UPLO, N, AP, IPIV, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SSPTRI

  SUBROUTINE DSPTRI(UPLO, N, AP, IPIV, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DSPTRI

  SUBROUTINE CSPTRI(UPLO, N, AP, IPIV, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CSPTRI

  SUBROUTINE ZSPTRI(UPLO, N, AP, IPIV, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZSPTRI

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPRFS

  SUBROUTINE SSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,  &
 &                   FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SSPRFS

  SUBROUTINE DSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,  &
 &                   FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DSPRFS

  SUBROUTINE CSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,  &
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CSPRFS

  SUBROUTINE ZSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,  &
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZSPRFS

  MODULE PROCEDURE SSPRFS1
  MODULE PROCEDURE DSPRFS1
  MODULE PROCEDURE CSPRFS1
  MODULE PROCEDURE ZSPRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPCON

  SUBROUTINE SSPCON(UPLO, N, AP, IPIV, ANORM, RCOND, WORK, IWORK,  &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SSPCON

  SUBROUTINE DSPCON(UPLO, N, AP, IPIV, ANORM, RCOND, WORK, IWORK,  &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DSPCON

  SUBROUTINE CSPCON(UPLO, N, AP, IPIV, ANORM, RCOND, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CSPCON

  SUBROUTINE ZSPCON(UPLO, N, AP, IPIV, ANORM, RCOND, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZSPCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPTRS

  SUBROUTINE SSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE SSPTRS

  SUBROUTINE DSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DSPTRS

  SUBROUTINE CSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CSPTRS

  SUBROUTINE ZSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZSPTRS

  MODULE PROCEDURE SSPTRS1
  MODULE PROCEDURE DSPTRS1
  MODULE PROCEDURE CSPTRS1
  MODULE PROCEDURE ZSPTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPTRF

  SUBROUTINE SSPTRF(UPLO, N, AP, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE SSPTRF

  SUBROUTINE DSPTRF(UPLO, N, AP, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE DSPTRF

  SUBROUTINE CSPTRF(UPLO, N, AP, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE CSPTRF

  SUBROUTINE ZSPTRF(UPLO, N, AP, IPIV, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE ZSPTRF

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPEVX

  SUBROUTINE SSPEVX(JOBZ, RANGE, UPLO, N, AP, VL, VU, IL, IU,     &
&                    ABSTOL, M, W, Z, LDZ, WORK, IWORK, IFAIL,     &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO, RANGE
    INTEGER, INTENT(IN) :: LDZ, N, IL, IU
    INTEGER, INTENT(OUT) :: INFO, IWORK(*), M, IFAIL(*)
    REAL(WP), INTENT(IN) :: VL, VU, ABSTOL
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE SSPEVX

  SUBROUTINE DSPEVX(JOBZ, RANGE, UPLO, N, AP, VL, VU, IL, IU,     &
&                    ABSTOL, M, W, Z, LDZ, WORK, IWORK, IFAIL,     &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO, RANGE
    INTEGER, INTENT(IN) :: LDZ, N, IL, IU
    INTEGER, INTENT(OUT) :: INFO, IWORK(*), M, IFAIL(*)
    REAL(WP), INTENT(IN) :: VL, VU, ABSTOL
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE DSPEVX

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPEVD

  SUBROUTINE SSPEVD(JOBZ, UPLO, N, AP, W, Z, LDZ, WORK, LWORK,    &
&                    IWORK, LIWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO
    INTEGER, INTENT(IN) :: LDZ, N, LWORK, LIWORK
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE SSPEVD

  SUBROUTINE DSPEVD(JOBZ, UPLO, N, AP, W, Z, LDZ, WORK, LWORK,    &
&                    IWORK, LIWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO
    INTEGER, INTENT(IN) :: LDZ, N, LWORK, LIWORK
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE DSPEVD

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPEV

  SUBROUTINE SSPEV(JOBZ, UPLO, N, AP, W, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO
    INTEGER, INTENT(IN) :: LDZ, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE SSPEV

  SUBROUTINE DSPEV(JOBZ, UPLO, N, AP, W, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: JOBZ, UPLO
    INTEGER, INTENT(IN) :: LDZ, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
    REAL(WP), INTENT(OUT) :: W(*), Z(LDZ, *), WORK(*)
  END SUBROUTINE DSPEV

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPSV

  SUBROUTINE SSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE SSPSV

  SUBROUTINE DSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE DSPSV

  SUBROUTINE CSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE CSPSV

  SUBROUTINE ZSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(IN) :: IPIV(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE ZSPSV

  MODULE PROCEDURE SSPSV1
  MODULE PROCEDURE DSPSV1
  MODULE PROCEDURE CSPSV1
  MODULE PROCEDURE ZSPSV1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_SPSVX

  SUBROUTINE SSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X,  &
&                    LDX, RCOND, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(OUT) :: IWORK(*)
    INTEGER, INTENT(INOUT) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: A(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: AF(*)
  END SUBROUTINE SSPSVX

  SUBROUTINE DSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X,  &
&                    LDX, RCOND, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(OUT) :: IWORK(*)
    INTEGER, INTENT(INOUT) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: A(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: AF(*)
  END SUBROUTINE DSPSVX

  SUBROUTINE CSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X,  &
&                    LDX, RCOND, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(INOUT) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    COMPLEX(WP), INTENT(IN) :: A(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: AF(*)
  END SUBROUTINE CSPSVX

  SUBROUTINE ZSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X,  &
&                    LDX, RCOND, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(INOUT) :: IPIV(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    COMPLEX(WP), INTENT(IN) :: A(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: AF(*)
  END SUBROUTINE ZSPSVX

  MODULE PROCEDURE SSPSVX1
  MODULE PROCEDURE DSPSVX1
  MODULE PROCEDURE CSPSVX1
  MODULE PROCEDURE ZSPSVX1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE CSPRFS1(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX, &
&                    FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
  COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, &
&                         LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CSPRFS
  END INTERFACE
  REAL(WP) :: FERR1(1), BERR1(1)
  CALL CSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,     &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE CSPRFS1

SUBROUTINE ZSPRFS1(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX, &
&                    FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
  COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, &
&                         LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZSPRFS
  END INTERFACE
  REAL(WP) :: FERR1(1), BERR1(1)
  CALL ZSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,     &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE ZSPRFS1

SUBROUTINE SSPRFS1(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX, &
&                    FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
  REAL(WP), INTENT(INOUT) :: X(LDX, *)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE SSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, &
&                         LDX, FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE SSPRFS
  END INTERFACE
  REAL(WP) :: FERR1(1), BERR1(1)
  CALL SSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,     &
&                FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE SSPRFS1

SUBROUTINE DSPRFS1(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX, &
&                    FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
  REAL(WP), INTENT(INOUT) :: X(LDX, *)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE DSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, &
&                         LDX, FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE DSPRFS
  END INTERFACE
  REAL(WP) :: FERR1(1), BERR1(1)
  CALL DSPRFS(UPLO, N, NRHS, AP, AFP, IPIV, B, LDB, X, LDX,     &
&                FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE DSPRFS1

SUBROUTINE SSPTRS1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE SSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE SSPTRS
  END INTERFACE
  CALL SSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE SSPTRS1

SUBROUTINE DSPTRS1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE DSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE DSPTRS
  END INTERFACE
  CALL DSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE DSPTRS1

SUBROUTINE CSPTRS1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE CSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE CSPTRS
  END INTERFACE
  CALL CSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE CSPTRS1

SUBROUTINE ZSPTRS1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE ZSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE ZSPTRS
  END INTERFACE
  CALL ZSPTRS(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE ZSPTRS1

SUBROUTINE SSPSV1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE SSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE SSPSV
  END INTERFACE
  CALL SSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE SSPSV1

SUBROUTINE DSPSV1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  REAL(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE DSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE DSPSV
  END INTERFACE
  CALL DSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE DSPSV1

SUBROUTINE CSPSV1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  COMPLEX(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE CSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE CSPSV
  END INTERFACE
  CALL CSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE CSPSV1

SUBROUTINE ZSPSV1(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(IN) :: IPIV(*)
  COMPLEX(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE ZSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(IN) :: IPIV(*)
      COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE ZSPSV
  END INTERFACE
  CALL ZSPSV(UPLO, N, NRHS, AP, IPIV, B, LDB, INFO)
END SUBROUTINE ZSPSV1

SUBROUTINE SSPSVX1(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, &
&                     LDX, RCOND, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(OUT) :: IWORK(*)
  INTEGER, INTENT(INOUT) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: A(*), B(*)
  REAL(WP), INTENT(INOUT) :: AF(*)
  INTERFACE
    SUBROUTINE SSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, &
&                        X, LDX, RCOND, FERR, BERR, WORK, IWORK,   &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(OUT) :: IWORK(*)
      INTEGER, INTENT(INOUT) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: A(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: AF(*)
    END SUBROUTINE SSPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL SSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, LDX, &
&                RCOND, LFERR, LBERR, WORK, IWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE SSPSVX1

SUBROUTINE DSPSVX1(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, &
&                     LDX, RCOND, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(OUT) :: IWORK(*)
  INTEGER, INTENT(INOUT) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: A(*), B(*)
  REAL(WP), INTENT(INOUT) :: AF(*)
  INTERFACE
    SUBROUTINE DSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, &
&                        X, LDX, RCOND, FERR, BERR, WORK, IWORK,   &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(OUT) :: IWORK(*)
      INTEGER, INTENT(INOUT) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: A(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: AF(*)
    END SUBROUTINE DSPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL DSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, LDX, &
&                RCOND, LFERR, LBERR, WORK, IWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE DSPSVX1

SUBROUTINE CSPSVX1(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, &
&                     LDX, RCOND, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(INOUT) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  COMPLEX(WP), INTENT(IN) :: A(*), B(*)
  COMPLEX(WP), INTENT(INOUT) :: AF(*)
  INTERFACE
    SUBROUTINE CSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, &
&                        X, LDX, RCOND, FERR, BERR, WORK, RWORK,   &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(INOUT) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      COMPLEX(WP), INTENT(IN) :: A(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: AF(*)
    END SUBROUTINE CSPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL CSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, LDX, &
&                RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE CSPSVX1

SUBROUTINE ZSPSVX1(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, &
&                     LDX, RCOND, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(INOUT) :: IPIV(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  COMPLEX(WP), INTENT(IN) :: A(*), B(*)
  COMPLEX(WP), INTENT(INOUT) :: AF(*)
  INTERFACE
    SUBROUTINE ZSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, &
&                        X, LDX, RCOND, FERR, BERR, WORK, RWORK,   &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO, FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(INOUT) :: IPIV(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      COMPLEX(WP), INTENT(IN) :: A(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: AF(*)
    END SUBROUTINE ZSPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL ZSPSVX(FACT, UPLO, N, NRHS, A, AF, IPIV, B, LDB, X, LDX, &
&                RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE ZSPSVX1

END MODULE F77_SP_LAPACK
