! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_PT_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTEQR

  SUBROUTINE SPTEQR(COMPZ, N, D, E, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPZ
    INTEGER, INTENT(IN) :: INFO, LDZ, N
    REAL(WP), INTENT(INOUT) :: D(*), E(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
    REAL(WP), INTENT(INOUT) :: Z(LDZ, *)
  END SUBROUTINE SPTEQR

  SUBROUTINE DPTEQR(COMPZ, N, D, E, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPZ
    INTEGER, INTENT(IN) :: INFO, LDZ, N
    REAL(WP), INTENT(INOUT) :: D(*), E(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
    REAL(WP), INTENT(INOUT) :: Z(LDZ, *)
  END SUBROUTINE DPTEQR

  SUBROUTINE CPTEQR(COMPZ, N, D, E, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPZ
    INTEGER, INTENT(IN) :: INFO, LDZ, N
    REAL(WP), INTENT(INOUT) :: D(*), E(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
    COMPLEX(WP), INTENT(INOUT) :: Z(LDZ, *)
  END SUBROUTINE CPTEQR

  SUBROUTINE ZPTEQR(COMPZ, N, D, E, Z, LDZ, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPZ
    INTEGER, INTENT(IN) :: INFO, LDZ, N
    REAL(WP), INTENT(INOUT) :: D(*), E(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
    COMPLEX(WP), INTENT(INOUT) :: Z(LDZ, *)
  END SUBROUTINE ZPTEQR

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTRFS

  SUBROUTINE SPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR,   &
 &                   BERR, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*), DF(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SPTRFS

  SUBROUTINE DPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR,   &
 &                   BERR, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*), DF(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DPTRFS

  SUBROUTINE CPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,   &
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*), DF(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CPTRFS

  SUBROUTINE ZPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,   &
 &                   FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*), DF(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZPTRFS

  MODULE PROCEDURE SPTRFS1
  MODULE PROCEDURE DPTRFS1
  MODULE PROCEDURE CPTRFS1
  MODULE PROCEDURE ZPTRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTCON

  SUBROUTINE SPTCON(N, D, E, ANORM, RCOND, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM, D(*)
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    REAL(WP), INTENT(IN) :: E(*)
  END SUBROUTINE SPTCON

  SUBROUTINE DPTCON(N, D, E, ANORM, RCOND, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM, D(*)
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    REAL(WP), INTENT(IN) :: E(*)
  END SUBROUTINE DPTCON

  SUBROUTINE CPTCON(N, D, E, ANORM, RCOND, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM, D(*)
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: E(*)
  END SUBROUTINE CPTCON

  SUBROUTINE ZPTCON(N, D, E, ANORM, RCOND, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM, D(*)
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: E(*)
  END SUBROUTINE ZPTCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTTRS

  SUBROUTINE SPTTRS(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*)
    REAL(WP), INTENT(IN) :: E(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE SPTTRS

  SUBROUTINE DPTTRS(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*)
    REAL(WP), INTENT(IN) :: E(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DPTTRS

  SUBROUTINE CPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*)
    COMPLEX(WP), INTENT(IN) :: E(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CPTTRS

  SUBROUTINE ZPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: D(*)
    COMPLEX(WP), INTENT(IN) :: E(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZPTTRS

  MODULE PROCEDURE SPTTRS1
  MODULE PROCEDURE DPTTRS1
  MODULE PROCEDURE CPTTRS1
  MODULE PROCEDURE ZPTTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTTRF

  SUBROUTINE SPTTRF(N, D, E, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    REAL(WP), INTENT(INOUT) :: E(*)
  END SUBROUTINE SPTTRF

  SUBROUTINE DPTTRF(N, D, E, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    REAL(WP), INTENT(INOUT) :: E(*)
  END SUBROUTINE DPTTRF

  SUBROUTINE CPTTRF(N, D, E, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    COMPLEX(WP), INTENT(INOUT) :: E(*)
  END SUBROUTINE CPTTRF

  SUBROUTINE ZPTTRF(N, D, E, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    COMPLEX(WP), INTENT(INOUT) :: E(*)
  END SUBROUTINE ZPTTRF

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTSV

  SUBROUTINE SPTSV(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    REAL(WP), INTENT(INOUT) :: E(*), B(LDB, *)
  END SUBROUTINE SPTSV

  SUBROUTINE DPTSV(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    REAL(WP), INTENT(INOUT) :: E(*), B(LDB, *)
  END SUBROUTINE DPTSV

  SUBROUTINE CPTSV(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    COMPLEX(WP), INTENT(INOUT) :: E(*), B(LDB, *)
  END SUBROUTINE CPTSV

  SUBROUTINE ZPTSV(N, NRHS, D, E, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: D(*)
    COMPLEX(WP), INTENT(INOUT) :: E(*), B(LDB, *)
  END SUBROUTINE ZPTSV

  MODULE PROCEDURE SPTSV1
  MODULE PROCEDURE DPTSV1
  MODULE PROCEDURE CPTSV1
  MODULE PROCEDURE ZPTSV1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PTSVX

  SUBROUTINE SPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    RCOND, FERR, BERR, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: D(*)
    REAL(WP), INTENT(IN) :: E(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: DF(*)
    REAL(WP), INTENT(INOUT) :: EF(*)
  END SUBROUTINE SPTSVX

  SUBROUTINE DPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    RCOND, FERR, BERR, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: D(*)
    REAL(WP), INTENT(IN) :: E(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: DF(*)
    REAL(WP), INTENT(INOUT) :: EF(*)
  END SUBROUTINE DPTSVX

  SUBROUTINE CPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    RCOND, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: D(*)
    COMPLEX(WP), INTENT(IN) :: E(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: DF(*)
    COMPLEX(WP), INTENT(INOUT) :: EF(*)
  END SUBROUTINE CPTSVX

  SUBROUTINE ZPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    RCOND, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: FACT
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(IN) :: D(*)
    COMPLEX(WP), INTENT(IN) :: E(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: DF(*)
    COMPLEX(WP), INTENT(INOUT) :: EF(*)
  END SUBROUTINE ZPTSVX

  MODULE PROCEDURE SPTSVX1
  MODULE PROCEDURE DPTSVX1
  MODULE PROCEDURE CPTSVX1
  MODULE PROCEDURE ZPTSVX1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE SPTRFS1(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR,  &
&                    BERR, WORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*), DF(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: B(*), E(*), EF(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE SPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX,   &
&                         FERR, BERR, WORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*), DF(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE SPTRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL SPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR1,     &
&                BERR1, WORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE SPTRFS1

SUBROUTINE DPTRFS1(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR,  &
&                    BERR, WORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*), DF(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: B(*), E(*), EF(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE DPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX,   &
&                         FERR, BERR, WORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*), DF(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE DPTRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL DPTRFS(N, NRHS, D, E, DF, EF, B, LDB, X, LDX, FERR1,     &
&                BERR1, WORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE DPTRFS1

SUBROUTINE CPTRFS1(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*), DF(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: B(*), E(*), EF(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X,  &
&                         LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*), DF(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CPTRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL CPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE CPTRFS1

SUBROUTINE ZPTRFS1(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,  &
&                    FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*), DF(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: B(*), E(*), EF(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X,  &
&                         LDX, FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*), DF(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: B(LDB, *), E(*), EF(*)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZPTRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL ZPTRFS(UPLO, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE ZPTRFS1

SUBROUTINE SPTTRS1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*)
  REAL(WP), INTENT(IN) :: E(*)
  REAL(WP), INTENT(OUT) :: B(*)
  INTERFACE
    SUBROUTINE SPTTRS(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*)
      REAL(WP), INTENT(IN) :: E(*)
      REAL(WP), INTENT(OUT) :: B(LDB, *)
    END SUBROUTINE SPTTRS
  END INTERFACE
  CALL SPTTRS(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE SPTTRS1

SUBROUTINE DPTTRS1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*)
  REAL(WP), INTENT(IN) :: E(*)
  REAL(WP), INTENT(OUT) :: B(*)
  INTERFACE
    SUBROUTINE DPTTRS(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*)
      REAL(WP), INTENT(IN) :: E(*)
      REAL(WP), INTENT(OUT) :: B(LDB, *)
    END SUBROUTINE DPTTRS
  END INTERFACE
  CALL DPTTRS(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE DPTTRS1

SUBROUTINE CPTTRS1(UPLO, N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*)
  COMPLEX(WP), INTENT(IN) :: E(*)
  COMPLEX(WP), INTENT(OUT) :: B(*)
  INTERFACE
    SUBROUTINE CPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*)
      COMPLEX(WP), INTENT(IN) :: E(*)
      COMPLEX(WP), INTENT(OUT) :: B(LDB, *)
    END SUBROUTINE CPTTRS
  END INTERFACE
  CALL CPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE CPTTRS1

SUBROUTINE ZPTTRS1(UPLO, N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: D(*)
  COMPLEX(WP), INTENT(IN) :: E(*)
  COMPLEX(WP), INTENT(OUT) :: B(*)
  INTERFACE
    SUBROUTINE ZPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: D(*)
      COMPLEX(WP), INTENT(IN) :: E(*)
      COMPLEX(WP), INTENT(OUT) :: B(LDB, *)
    END SUBROUTINE ZPTTRS
  END INTERFACE
  CALL ZPTTRS(UPLO, N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE ZPTTRS1

SUBROUTINE SPTSV1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: D(*)
  REAL(WP), INTENT(INOUT) :: E(*), B(*)
  INTERFACE
    SUBROUTINE SPTSV(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: D(*)
      REAL(WP), INTENT(INOUT) :: E(*), B(LDB, *)
    END SUBROUTINE SPTSV
  END INTERFACE
  CALL SPTSV(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE SPTSV1

SUBROUTINE DPTSV1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: D(*)
  REAL(WP), INTENT(INOUT) :: E(*), B(*)
  INTERFACE
    SUBROUTINE DPTSV(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: D(*)
      REAL(WP), INTENT(INOUT) :: E(*), B(LDB, *)
    END SUBROUTINE DPTSV
  END INTERFACE
  CALL DPTSV(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE DPTSV1

SUBROUTINE CPTSV1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: D(*)
  COMPLEX(WP), INTENT(INOUT) :: E(*), B(*)
  INTERFACE
    SUBROUTINE CPTSV(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: D(*)
      COMPLEX(WP), INTENT(INOUT) :: E(*), B(LDB, *)
    END SUBROUTINE CPTSV
  END INTERFACE
  CALL CPTSV(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE CPTSV1

SUBROUTINE ZPTSV1(N, NRHS, D, E, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: D(*)
  COMPLEX(WP), INTENT(INOUT) :: E(*), B(*)
  INTERFACE
    SUBROUTINE ZPTSV(N, NRHS, D, E, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: D(*)
      COMPLEX(WP), INTENT(INOUT) :: E(*), B(LDB, *)
    END SUBROUTINE ZPTSV
  END INTERFACE
  CALL ZPTSV(N, NRHS, D, E, B, LDB, INFO)
END SUBROUTINE ZPTSV1

SUBROUTINE SPTSVX1(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX, &
&                     RCOND, FERR, BERR, WORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: D(*)
  REAL(WP), INTENT(IN) :: E(*), B(*)
  REAL(WP), INTENT(INOUT) :: DF(*)
  REAL(WP), INTENT(INOUT) :: EF(*)
  INTERFACE
    SUBROUTINE SPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X,   &
&                        LDX, RCOND, FERR, BERR, WORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: D(*)
      REAL(WP), INTENT(IN) :: E(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: DF(*)
      REAL(WP), INTENT(INOUT) :: EF(*)
    END SUBROUTINE SPTSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL SPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                RCOND, LFERR, LBERR, WORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE SPTSVX1

SUBROUTINE DPTSVX1(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX, &
&                     RCOND, FERR, BERR, WORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: D(*)
  REAL(WP), INTENT(IN) :: E(*), B(*)
  REAL(WP), INTENT(INOUT) :: DF(*)
  REAL(WP), INTENT(INOUT) :: EF(*)
  INTERFACE
    SUBROUTINE DPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X,   &
&                        LDX, RCOND, FERR, BERR, WORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: D(*)
      REAL(WP), INTENT(IN) :: E(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: DF(*)
      REAL(WP), INTENT(INOUT) :: EF(*)
    END SUBROUTINE DPTSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL DPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                RCOND, LFERR, LBERR, WORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE DPTSVX1

SUBROUTINE CPTSVX1(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX, &
&                     RCOND, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: D(*)
  COMPLEX(WP), INTENT(IN) :: E(*), B(*)
  REAL(WP), INTENT(INOUT) :: DF(*)
  COMPLEX(WP), INTENT(INOUT) :: EF(*)
  INTERFACE
    SUBROUTINE CPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X,   &
&                        LDX, RCOND, FERR, BERR, WORK, RWORK,      &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: D(*)
      COMPLEX(WP), INTENT(IN) :: E(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: DF(*)
      COMPLEX(WP), INTENT(INOUT) :: EF(*)
    END SUBROUTINE CPTSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL CPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE CPTSVX1

SUBROUTINE ZPTSVX1(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX, &
&                     RCOND, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: FACT
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(IN) :: D(*)
  COMPLEX(WP), INTENT(IN) :: E(*), B(*)
  REAL(WP), INTENT(INOUT) :: DF(*)
  COMPLEX(WP), INTENT(INOUT) :: EF(*)
  INTERFACE
    SUBROUTINE ZPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X,   &
&                        LDX, RCOND, FERR, BERR, WORK, RWORK,      &
&                        INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: FACT
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(IN) :: D(*)
      COMPLEX(WP), INTENT(IN) :: E(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: DF(*)
      COMPLEX(WP), INTENT(INOUT) :: EF(*)
    END SUBROUTINE ZPTSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL ZPTSVX(FACT, N, NRHS, D, E, DF, EF, B, LDB, X, LDX,      &
&                RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE ZPTSVX1

END MODULE F77_PT_LAPACK
