! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_TR_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRSEN

  SUBROUTINE STRSEN(JOB, COMPQ, SELECT, N, T, LDT, Q, LDQ, WR, WI, &
 &                   M, S, SEP, WORK, LWORK, IWORK, LIWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ, JOB
    INTEGER, INTENT(IN) :: LDQ, LDT, LWORK, N, LIWORK
    INTEGER, INTENT(OUT) :: INFO, M, IWORK(LIWORK)
    REAL(WP), INTENT(OUT) :: S, SEP
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
    REAL(WP), INTENT(IN) :: WR(*), WI(*)
    REAL(WP), INTENT(OUT) :: WORK(LWORK)
  END SUBROUTINE STRSEN

  SUBROUTINE DTRSEN(JOB, COMPQ, SELECT, N, T, LDT, Q, LDQ, WR, WI, &
 &                   M, S, SEP, WORK, LWORK, IWORK, LIWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ, JOB
    INTEGER, INTENT(IN) :: LDQ, LDT, LWORK, N, LIWORK
    INTEGER, INTENT(OUT) :: INFO, M, IWORK(LIWORK)
    REAL(WP), INTENT(OUT) :: S, SEP
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
    REAL(WP), INTENT(IN) :: WR(*), WI(*)
    REAL(WP), INTENT(OUT) :: WORK(LWORK)
  END SUBROUTINE DTRSEN

  SUBROUTINE CTRSEN(JOB, COMPQ, SELECT, N, T, LDT, Q, LDQ, W, M, S,&
 &                   SEP, WORK, LWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ, JOB
    INTEGER, INTENT(IN) :: LDQ, LDT, LWORK, N
    INTEGER, INTENT(OUT) :: INFO, M
    REAL(WP), INTENT(OUT) :: S, SEP
    LOGICAL, INTENT(IN) :: SELECT(*)
    COMPLEX(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
    COMPLEX(WP), INTENT(IN) :: W(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(LWORK)
  END SUBROUTINE CTRSEN

  SUBROUTINE ZTRSEN(JOB, COMPQ, SELECT, N, T, LDT, Q, LDQ, W, M, S,&
 &                   SEP, WORK, LWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ, JOB
    INTEGER, INTENT(IN) :: LDQ, LDT, LWORK, N
    INTEGER, INTENT(OUT) :: INFO, M
    REAL(WP), INTENT(OUT) :: S, SEP
    LOGICAL, INTENT(IN) :: SELECT(*)
    COMPLEX(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
    COMPLEX(WP), INTENT(IN) :: W(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(LWORK)
  END SUBROUTINE ZTRSEN

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRSNA

  SUBROUTINE STRSNA(JOB, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR,  &
 &                   LDVR, S, SEP, MM, M, WORK, LDWORK, IWORK,      &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, JOB
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, LDWORK, MM, N
    INTEGER, INTENT(OUT) :: INFO, M, IWORK(*)
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: S(*), SEP(*)
    REAL(WP), INTENT(IN) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    REAL(WP), INTENT(OUT) :: WORK(LDWORK, *)
  END SUBROUTINE STRSNA

  SUBROUTINE DTRSNA(JOB, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR,  &
 &                   LDVR, S, SEP, MM, M, WORK, LDWORK, IWORK,      &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, JOB
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, LDWORK, MM, N
    INTEGER, INTENT(OUT) :: INFO, M, IWORK(*)
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: S(*), SEP(*)
    REAL(WP), INTENT(IN) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    REAL(WP), INTENT(OUT) :: WORK(LDWORK, *)
  END SUBROUTINE DTRSNA

  SUBROUTINE CTRSNA(JOB, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR,  &
 &                   LDVR, S, SEP, MM, M, WORK, LDWORK, RWORK,      &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, JOB
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, LDWORK, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: RWORK(*), S(*), SEP(*)
    COMPLEX(WP), INTENT(IN) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(LDWORK, *)
  END SUBROUTINE CTRSNA

  SUBROUTINE ZTRSNA(JOB, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR,  &
 &                   LDVR, S, SEP, MM, M, WORK, LDWORK, RWORK,      &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, JOB
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, LDWORK, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(IN) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: RWORK(*), S(*), SEP(*)
    COMPLEX(WP), INTENT(IN) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(LDWORK, *)
  END SUBROUTINE ZTRSNA

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRSYL

  SUBROUTINE STRSYL(TRANA, TRANB, ISGN, M, N, A, LDA, B, LDB, C,   &
 &                   LDC, SCALE, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: TRANA, TRANB
    INTEGER, INTENT(IN) :: ISGN, LDA, LDB, LDC, M, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: SCALE
    REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: C(LDC, *)
  END SUBROUTINE STRSYL

  SUBROUTINE DTRSYL(TRANA, TRANB, ISGN, M, N, A, LDA, B, LDB, C,   &
 &                   LDC, SCALE, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: TRANA, TRANB
    INTEGER, INTENT(IN) :: ISGN, LDA, LDB, LDC, M, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: SCALE
    REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: C(LDC, *)
  END SUBROUTINE DTRSYL

  SUBROUTINE CTRSYL(TRANA, TRANB, ISGN, M, N, A, LDA, B, LDB, C,   &
 &                   LDC, SCALE, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: TRANA, TRANB
    INTEGER, INTENT(IN) :: ISGN, LDA, LDB, LDC, M, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: SCALE
    COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC, *)
  END SUBROUTINE CTRSYL

  SUBROUTINE ZTRSYL(TRANA, TRANB, ISGN, M, N, A, LDA, B, LDB, C,   &
 &                   LDC, SCALE, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: TRANA, TRANB
    INTEGER, INTENT(IN) :: ISGN, LDA, LDB, LDC, M, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: SCALE
    COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC, *)
  END SUBROUTINE ZTRSYL

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TREXC

  SUBROUTINE STREXC(COMPQ, N, T, LDT, Q, LDQ, IFST, ILST, WORK,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ
    INTEGER, INTENT(IN) :: IFST, ILST, LDQ, LDT, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *), WORK(*)
  END SUBROUTINE STREXC

  SUBROUTINE DTREXC(COMPQ, N, T, LDT, Q, LDQ, IFST, ILST, WORK,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ
    INTEGER, INTENT(IN) :: IFST, ILST, LDQ, LDT, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *), WORK(*)
  END SUBROUTINE DTREXC

  SUBROUTINE CTREXC(COMPQ, N, T, LDT, Q, LDQ, IFST, ILST, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ
    INTEGER, INTENT(IN) :: IFST, ILST, LDQ, LDT, N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
  END SUBROUTINE CTREXC

  SUBROUTINE ZTREXC(COMPQ, N, T, LDT, Q, LDQ, IFST, ILST, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: COMPQ
    INTEGER, INTENT(IN) :: IFST, ILST, LDQ, LDT, N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: Q(LDQ, *), T(LDT, *)
  END SUBROUTINE ZTREXC

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TREVC

  SUBROUTINE STREVC(SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR, &
 &                   LDVR, MM, M, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, SIDE
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(INOUT) :: SELECT(*)
    REAL(WP), INTENT(IN) :: T(LDT, *)
    REAL(WP), INTENT(INOUT) :: VL(LDVL, *), VR(LDVR, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STREVC

  SUBROUTINE DTREVC(SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR, &
 &                   LDVR, MM, M, WORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, SIDE
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(INOUT) :: SELECT(*)
    REAL(WP), INTENT(IN) :: T(LDT, *)
    REAL(WP), INTENT(INOUT) :: VL(LDVL, *), VR(LDVR, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTREVC

  SUBROUTINE CTREVC(SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR, &
 &                   LDVR, MM, M, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, SIDE
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(INOUT) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: RWORK(*)
    COMPLEX(WP), INTENT(INOUT) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTREVC

  SUBROUTINE ZTREVC(SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL, VR, &
 &                   LDVR, MM, M, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: HOWMNY, SIDE
    INTEGER, INTENT(IN) :: LDT, LDVL, LDVR, MM, N
    INTEGER, INTENT(OUT) :: INFO, M
    LOGICAL, INTENT(INOUT) :: SELECT(*)
    REAL(WP), INTENT(OUT) :: RWORK(*)
    COMPLEX(WP), INTENT(INOUT) :: T(LDT, *), VL(LDVL, *), VR(LDVR, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTREVC

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRTRI

  SUBROUTINE STRTRI(UPLO, DIAG, N, A, LDA, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: A(LDA, *)
  END SUBROUTINE STRTRI

  SUBROUTINE DTRTRI(UPLO, DIAG, N, A, LDA, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: A(LDA, *)
  END SUBROUTINE DTRTRI

  SUBROUTINE CTRTRI(UPLO, DIAG, N, A, LDA, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(LDA, *)
  END SUBROUTINE CTRTRI

  SUBROUTINE ZTRTRI(UPLO, DIAG, N, A, LDA, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: A(LDA, *)
  END SUBROUTINE ZTRTRI

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRRFS

  SUBROUTINE STRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X, &
 &                   LDX, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    REAL(WP), INTENT(IN) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STRRFS

  SUBROUTINE DTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X, &
 &                   LDX, FERR, BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    REAL(WP), INTENT(IN) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTRRFS

  SUBROUTINE CTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X, &
 &                   LDX, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTRRFS

  SUBROUTINE ZTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X, &
 &                   LDX, FERR, BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTRRFS

  MODULE PROCEDURE STRRFS1
  MODULE PROCEDURE DTRRFS1
  MODULE PROCEDURE CTRRFS1
  MODULE PROCEDURE ZTRRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRCON

  SUBROUTINE STRCON(NORM, UPLO, DIAG, N, A, LDA, RCOND, WORK,      &
 &                   IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: A(LDA, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE STRCON

  SUBROUTINE DTRCON(NORM, UPLO, DIAG, N, A, LDA, RCOND, WORK,      &
 &                   IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: A(LDA, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DTRCON

  SUBROUTINE CTRCON(NORM, UPLO, DIAG, N, A, LDA, RCOND, WORK,      &
 &                   RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: A(LDA, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CTRCON

  SUBROUTINE ZTRCON(NORM, UPLO, DIAG, N, A, LDA, RCOND, WORK,      &
 &                   RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, NORM, UPLO
    INTEGER, INTENT(IN) :: LDA, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: A(LDA, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZTRCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_TRTRS

  SUBROUTINE STRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: A(LDA, *)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE STRTRS

  SUBROUTINE DTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: A(LDA, *)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DTRTRS

  SUBROUTINE CTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: A(LDA, *)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CTRTRS

  SUBROUTINE ZTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,    &
 &                   INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
    INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: A(LDA, *)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZTRTRS

  MODULE PROCEDURE STRTRS1
  MODULE PROCEDURE DTRTRS1
  MODULE PROCEDURE CTRTRS1
  MODULE PROCEDURE ZTRTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE STRTRS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,   &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: A(LDA, *)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE STRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: A(LDA, *)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE STRTRS
  END INTERFACE
  CALL STRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,       &
&                INFO)
END SUBROUTINE STRTRS1

SUBROUTINE DTRTRS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,   &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: A(LDA, *)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE DTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: A(LDA, *)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE DTRTRS
  END INTERFACE
  CALL DTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,       &
&                INFO)
END SUBROUTINE DTRTRS1

SUBROUTINE CTRTRS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,   &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: A(LDA, *)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE CTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: A(LDA, *)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE CTRTRS
  END INTERFACE
  CALL CTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,       &
&                INFO)
END SUBROUTINE CTRTRS1

SUBROUTINE ZTRTRS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,   &
&                    INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: A(LDA, *)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE ZTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: A(LDA, *)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE ZTRTRS
  END INTERFACE
  CALL ZTRTRS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB,       &
&                INFO)
END SUBROUTINE ZTRTRS1

SUBROUTINE STRRFS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,&
&                    LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: A(LDA, *), B(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE STRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, X, LDX, FERR, BERR, WORK, IWORK,    &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE STRRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL STRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,    &
&                LDX, FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE STRRFS1

SUBROUTINE DTRRFS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,&
&                    LDX, FERR, BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: A(LDA, *), B(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE DTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, X, LDX, FERR, BERR, WORK, IWORK,    &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE DTRRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL DTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,    &
&                LDX, FERR1, BERR1, WORK, IWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE DTRRFS1

SUBROUTINE CTRRFS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,&
&                    LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, X, LDX, FERR, BERR, WORK, RWORK,    &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CTRRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL CTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,    &
&                LDX, FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE CTRRFS1

SUBROUTINE ZTRRFS1(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,&
&                    LDX, FERR, BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
  INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B,   &
&                         LDB, X, LDX, FERR, BERR, WORK, RWORK,    &
&                         INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: DIAG, TRANS, UPLO
      INTEGER, INTENT(IN) :: LDA, LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: A(LDA, *), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZTRRFS
  END INTERFACE
  REAL(WP) FERR1(1), BERR1(1)
  CALL ZTRRFS(UPLO, TRANS, DIAG, N, NRHS, A, LDA, B, LDB, X,    &
&                LDX, FERR1, BERR1, WORK, RWORK, INFO)
  FERR = FERR1(1); BERR = BERR1(1)
END SUBROUTINE ZTRRFS1

END MODULE F77_TR_LAPACK
