! This program is a part of EASIFEM library
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

MODULE F77_PP_LAPACK

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPEQU

  SUBROUTINE SPPEQU(UPLO, N, AP, S, SCOND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: AMAX, SCOND, S(*)
    REAL(WP), INTENT(IN) :: AP(*)
  END SUBROUTINE SPPEQU

  SUBROUTINE DPPEQU(UPLO, N, AP, S, SCOND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: AMAX, SCOND, S(*)
    REAL(WP), INTENT(IN) :: AP(*)
  END SUBROUTINE DPPEQU

  SUBROUTINE CPPEQU(UPLO, N, AP, S, SCOND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: AMAX, SCOND, S(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
  END SUBROUTINE CPPEQU

  SUBROUTINE ZPPEQU(UPLO, N, AP, S, SCOND, AMAX, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: AMAX, SCOND, S(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
  END SUBROUTINE ZPPEQU

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPTRI

  SUBROUTINE SPPTRI(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE SPPTRI

  SUBROUTINE DPPTRI(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE DPPTRI

  SUBROUTINE CPPTRI(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE CPPTRI

  SUBROUTINE ZPPTRI(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE ZPPTRI

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPRFS

  SUBROUTINE SPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR,  &
 &                   BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SPPRFS

  SUBROUTINE DPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR,  &
 &                   BERR, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
    REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    REAL(WP), INTENT(INOUT) :: X(LDX, *)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DPPRFS

  SUBROUTINE CPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR,  &
 &                   BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CPPRFS

  SUBROUTINE ZPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR,  &
 &                   BERR, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
    COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZPPRFS

  MODULE PROCEDURE SPPRFS1
  MODULE PROCEDURE DPPRFS1
  MODULE PROCEDURE CPPRFS1
  MODULE PROCEDURE ZPPRFS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPCON

  SUBROUTINE SPPCON(UPLO, N, AP, ANORM, RCOND, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE SPPCON

  SUBROUTINE DPPCON(UPLO, N, AP, ANORM, RCOND, WORK, IWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO, IWORK(*)
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE DPPCON

  SUBROUTINE CPPCON(UPLO, N, AP, ANORM, RCOND, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE CPPCON

  SUBROUTINE ZPPCON(UPLO, N, AP, ANORM, RCOND, WORK, RWORK, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: ANORM
    REAL(WP), INTENT(OUT) :: RCOND, RWORK(*)
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(OUT) :: WORK(*)
  END SUBROUTINE ZPPCON

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPTRS

  SUBROUTINE SPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE SPPTRS

  SUBROUTINE DPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(IN) :: AP(*)
    REAL(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE DPPTRS

  SUBROUTINE CPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE CPPTRS

  SUBROUTINE ZPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: LDB, N, NRHS
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(IN) :: AP(*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
  END SUBROUTINE ZPPTRS

  MODULE PROCEDURE SPPTRS1
  MODULE PROCEDURE DPPTRS1
  MODULE PROCEDURE CPPTRS1
  MODULE PROCEDURE ZPPTRS1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPTRF

  SUBROUTINE SPPTRF(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE SPPTRF

  SUBROUTINE DPPTRF(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE DPPTRF

  SUBROUTINE CPPTRF(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE CPPTRF

  SUBROUTINE ZPPTRF(UPLO, N, AP, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*)
  END SUBROUTINE ZPPTRF

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPSV

  SUBROUTINE SPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE SPPSV

  SUBROUTINE DPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE DPPSV

  SUBROUTINE CPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE CPPSV

  SUBROUTINE ZPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    INTEGER, INTENT(IN) :: NRHS, N, LDB
    INTEGER, INTENT(OUT) :: INFO
    COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
  END SUBROUTINE ZPPSV

  MODULE PROCEDURE SPPSV1
  MODULE PROCEDURE DPPSV1
  MODULE PROCEDURE CPPSV1
  MODULE PROCEDURE ZPPSV1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

INTERFACE LA_PPSVX

  SUBROUTINE SPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,    &
&                    LDB, X, LDX, RCOND, FERR, BERR, WORK, IWORK,  &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
    CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(OUT) :: IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *), S(*)
  END SUBROUTINE SPPSVX

  SUBROUTINE DPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,    &
&                    LDB, X, LDX, RCOND, FERR, BERR, WORK, IWORK,  &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
    CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    INTEGER, INTENT(OUT) :: IWORK(*)
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
    REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *), S(*)
  END SUBROUTINE DPPSVX

  SUBROUTINE CPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,    &
&                    LDB, X, LDX, RCOND, FERR, BERR, WORK, RWORK,  &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => SP
    CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
    CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(INOUT) :: S(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *)
  END SUBROUTINE CPPSVX

  SUBROUTINE ZPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,    &
&                    LDB, X, LDX, RCOND, FERR, BERR, WORK, RWORK,  &
&                    INFO)
    USE LA_PRECISION, ONLY: WP => DP
    CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
    CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
    INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
    INTEGER, INTENT(OUT) :: INFO
    REAL(WP), INTENT(OUT) :: RCOND
    REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
    COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
    REAL(WP), INTENT(INOUT) :: S(*)
    COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *)
  END SUBROUTINE ZPPSVX

  MODULE PROCEDURE SPPSVX1
  MODULE PROCEDURE DPPSVX1
  MODULE PROCEDURE CPPSVX1
  MODULE PROCEDURE ZPPSVX1

END INTERFACE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

CONTAINS

SUBROUTINE SPPRFS1(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR, &
&                    BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE SPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX,  &
&                         FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE SPPRFS
  END INTERFACE
  REAL(WP) :: BERR1(1), FERR1(1)
  CALL SPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR1,    &
&                BERR1, WORK, IWORK, INFO)
  BERR = BERR1(1); FERR = FERR1(1)
END SUBROUTINE SPPRFS1

SUBROUTINE DPPRFS1(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR, &
&                    BERR, WORK, IWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO, IWORK(*)
  REAL(WP), INTENT(OUT) :: BERR, FERR
  REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(*)
  REAL(WP), INTENT(INOUT) :: X(*)
  REAL(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE DPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX,  &
&                         FERR, BERR, WORK, IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO, IWORK(*)
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*)
      REAL(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      REAL(WP), INTENT(INOUT) :: X(LDX, *)
      REAL(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE DPPRFS
  END INTERFACE
  REAL(WP) :: BERR1(1), FERR1(1)
  CALL DPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR1,    &
&                BERR1, WORK, IWORK, INFO)
  BERR = BERR1(1); FERR = FERR1(1)
END SUBROUTINE DPPRFS1

SUBROUTINE CPPRFS1(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR, &
&                    BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE CPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX,  &
&                         FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE CPPRFS
  END INTERFACE
  REAL(WP) :: BERR1(1), FERR1(1)
  CALL CPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR1,    &
&                BERR1, WORK, RWORK, INFO)
  BERR = BERR1(1); FERR = FERR1(1)
END SUBROUTINE CPPRFS1

SUBROUTINE ZPPRFS1(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR, &
&                    BERR, WORK, RWORK, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: BERR, FERR, RWORK(*)
  COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(*)
  COMPLEX(WP), INTENT(INOUT) :: X(*)
  COMPLEX(WP), INTENT(OUT) :: WORK(*)
  INTERFACE
    SUBROUTINE ZPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX,  &
&                         FERR, BERR, WORK, RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, LDX, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: BERR(*), FERR(*), RWORK(*)
      COMPLEX(WP), INTENT(IN) :: AFP(*), AP(*), B(LDB, *)
      COMPLEX(WP), INTENT(INOUT) :: X(LDX, *)
      COMPLEX(WP), INTENT(OUT) :: WORK(*)
    END SUBROUTINE ZPPRFS
  END INTERFACE
  REAL(WP) :: BERR1(1), FERR1(1)
  CALL ZPPRFS(UPLO, N, NRHS, AP, AFP, B, LDB, X, LDX, FERR1,    &
&                BERR1, WORK, RWORK, INFO)
  BERR = BERR1(1); FERR = FERR1(1)
END SUBROUTINE ZPPRFS1

SUBROUTINE SPPTRS1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE SPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE SPPTRS
  END INTERFACE
  CALL SPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE SPPTRS1

SUBROUTINE DPPTRS1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(IN) :: AP(*)
  REAL(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE DPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(IN) :: AP(*)
      REAL(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE DPPTRS
  END INTERFACE
  CALL DPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE DPPTRS1

SUBROUTINE CPPTRS1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE CPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE CPPTRS
  END INTERFACE
  CALL CPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE CPPTRS1

SUBROUTINE ZPPTRS1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: LDB, N, NRHS
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(IN) :: AP(*)
  COMPLEX(WP), INTENT(INOUT) :: B(*)
  INTERFACE
    SUBROUTINE ZPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: LDB, N, NRHS
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(IN) :: AP(*)
      COMPLEX(WP), INTENT(INOUT) :: B(LDB, *)
    END SUBROUTINE ZPPTRS
  END INTERFACE
  CALL ZPPTRS(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE ZPPTRS1

SUBROUTINE SPPSV1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE SPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE SPPSV
  END INTERFACE
  CALL SPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE SPPSV1

SUBROUTINE DPPSV1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE DPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE DPPSV
  END INTERFACE
  CALL DPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE DPPSV1

SUBROUTINE CPPSV1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE CPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE CPPSV
  END INTERFACE
  CALL CPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE CPPSV1

SUBROUTINE ZPPSV1(UPLO, N, NRHS, AP, B, LDB, INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: NRHS, N, LDB
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(WP), INTENT(INOUT) :: AP(*), B(*)
  INTERFACE
    SUBROUTINE ZPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: UPLO
      INTEGER, INTENT(IN) :: NRHS, N, LDB
      INTEGER, INTENT(OUT) :: INFO
      COMPLEX(WP), INTENT(INOUT) :: AP(*), B(LDB, *)
    END SUBROUTINE ZPPSV
  END INTERFACE
  CALL ZPPSV(UPLO, N, NRHS, AP, B, LDB, INFO)
END SUBROUTINE ZPPSV1

SUBROUTINE SPPSVX1(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,   &
&                     LDB, X, LDX, RCOND, FERR, BERR, WORK, IWORK, &
&                     INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
  CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(OUT) :: IWORK(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(*), S(*)
  INTERFACE
    SUBROUTINE SPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,&
&                        LDB, X, LDX, RCOND, FERR, BERR, WORK,     &
&                        IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
      CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(OUT) :: IWORK(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *), S(*)
    END SUBROUTINE SPPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL SPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B, LDB, X,&
&                LDX, RCOND, LFERR, LBERR, WORK, IWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE SPPSVX1

SUBROUTINE DPPSVX1(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,   &
&                     LDB, X, LDX, RCOND, FERR, BERR, WORK, IWORK, &
&                     INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
  CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  INTEGER, INTENT(OUT) :: IWORK(*)
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR
  REAL(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(*), S(*)
  INTERFACE
    SUBROUTINE DPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,&
&                        LDB, X, LDX, RCOND, FERR, BERR, WORK,     &
&                        IWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
      CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      INTEGER, INTENT(OUT) :: IWORK(*)
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*)
      REAL(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *), S(*)
    END SUBROUTINE DPPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL DPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B, LDB, X,&
&                LDX, RCOND, LFERR, LBERR, WORK, IWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE DPPSVX1

SUBROUTINE CPPSVX1(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,   &
&                     LDB, X, LDX, RCOND, FERR, BERR, WORK, RWORK, &
&                     INFO)
  USE LA_PRECISION, ONLY: WP => SP
  CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
  CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(INOUT) :: S(*)
  COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(*)
  INTERFACE
    SUBROUTINE CPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,&
&                        LDB, X, LDX, RCOND, FERR, BERR, WORK,     &
&                        RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => SP
      CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
      CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(INOUT) :: S(*)
      COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *)
    END SUBROUTINE CPPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL CPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B, LDB, X,&
&                LDX, RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE CPPSVX1

SUBROUTINE ZPPSVX1(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,   &
&                     LDB, X, LDX, RCOND, FERR, BERR, WORK, RWORK, &
&                     INFO)
  USE LA_PRECISION, ONLY: WP => DP
  CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
  CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
  INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
  INTEGER, INTENT(OUT) :: INFO
  REAL(WP), INTENT(OUT) :: RCOND
  REAL(WP), INTENT(OUT) :: FERR, BERR, RWORK(*)
  COMPLEX(WP), INTENT(OUT) :: X(*), WORK(*)
  REAL(WP), INTENT(INOUT) :: S(*)
  COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(*)
  INTERFACE
    SUBROUTINE ZPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B,&
&                        LDB, X, LDX, RCOND, FERR, BERR, WORK,     &
&                        RWORK, INFO)
      USE LA_PRECISION, ONLY: WP => DP
      CHARACTER(LEN=1), INTENT(IN) :: FACT, UPLO
      CHARACTER(LEN=1), INTENT(INOUT) :: EQUED
      INTEGER, INTENT(IN) :: LDB, LDX, NRHS, N
      INTEGER, INTENT(OUT) :: INFO
      REAL(WP), INTENT(OUT) :: RCOND
      REAL(WP), INTENT(OUT) :: FERR(*), BERR(*), RWORK(*)
      COMPLEX(WP), INTENT(OUT) :: X(LDX, *), WORK(*)
      REAL(WP), INTENT(INOUT) :: S(*)
      COMPLEX(WP), INTENT(INOUT) :: AP(*), AFP(*), B(LDB, *)
    END SUBROUTINE ZPPSVX
  END INTERFACE
  REAL(WP) :: LFERR(1), LBERR(1)
  CALL ZPPSVX(FACT, UPLO, N, NRHS, AP, AFP, EQUED, S, B, LDB, X,&
&                LDX, RCOND, LFERR, LBERR, WORK, RWORK, INFO)
  FERR = LFERR(1); BERR = LBERR(1)
END SUBROUTINE ZPPSVX1

END MODULE F77_PP_LAPACK
